FROM ubuntu

RUN apt-get update
RUN apt-get install -y nginx 
RUN apt-get install -y wget 
RUN apt-get install -y unzip

WORKDIR /var/www/html

RUN wget -O content.zip -q http://www.oswd.org/design/download/id/3558/
RUN unzip -q content.zip 
RUN mv bookish/* .

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
